# Generated by Django 5.2.5 on 2025-08-19 17:46

import clickhouse_backend.models
import django.db.models.manager
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_date', clickhouse_backend.models.DateField()),
                ('metric_name', clickhouse_backend.models.StringField(max_length=100)),
                ('metric_value', clickhouse_backend.models.UInt64Field()),
            ],
            options={
                'ordering': ['-metric_date', 'metric_name'],
                'engine': clickhouse_backend.models.SummingMergeTree(order_by=('metric_date', 'metric_name'), partition_by=clickhouse_backend.models.toYYYYMM('metric_date')),
                'indexes': [clickhouse_backend.models.Index(fields=['metric_name'], granularity=4, name='metric_name_set_idx', type=clickhouse_backend.models.Set(1000))],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceTest',
            fields=[
                ('id', clickhouse_backend.models.UInt64Field(primary_key=True, serialize=False)),
                ('timestamp', clickhouse_backend.models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', clickhouse_backend.models.UInt32Field()),
                ('category', clickhouse_backend.models.StringField(choices=[('A', 'Category A'), ('B', 'Category B'), ('C', 'Category C'), ('D', 'Category D'), ('E', 'Category E')], low_cardinality=True, max_length=1)),
                ('value', clickhouse_backend.models.Float64Field()),
                ('metadata', clickhouse_backend.models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-timestamp'],
                'engine': clickhouse_backend.models.MergeTree(index_granularity=8192, order_by=('timestamp', 'user_id'), partition_by=clickhouse_backend.models.toYYYYMM('timestamp')),
                'indexes': [clickhouse_backend.models.Index(fields=['category'], granularity=4, name='category_set_idx', type=clickhouse_backend.models.Set(10)), clickhouse_backend.models.Index(fields=['user_id'], granularity=1, name='performance_user_id_bloom_idx', type=clickhouse_backend.models.BloomFilter(0.01))],
                'constraints': [models.CheckConstraint(condition=models.Q(('value__gte', 0), ('value__lte', 10000)), name='value_range')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', clickhouse_backend.models.DateField(default=django.utils.timezone.now)),
                ('event_time', clickhouse_backend.models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', clickhouse_backend.models.UInt32Field()),
                ('session_id', clickhouse_backend.models.StringField(max_length=100)),
                ('event_type', clickhouse_backend.models.StringField(choices=[('page_view', 'Page View'), ('click', 'Click'), ('purchase', 'Purchase'), ('signup', 'Sign Up'), ('login', 'Login'), ('logout', 'Logout')], low_cardinality=True, max_length=20)),
                ('page_url', clickhouse_backend.models.StringField(max_length=500)),
                ('user_agent', clickhouse_backend.models.StringField(max_length=500)),
                ('country_code', clickhouse_backend.models.FixedStringField(max_bytes=2)),
                ('city', clickhouse_backend.models.StringField(low_cardinality=True, max_length=100)),
                ('referrer', clickhouse_backend.models.StringField(default='', max_length=500)),
                ('device_type', clickhouse_backend.models.StringField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet')], low_cardinality=True, max_length=10)),
                ('response_time_ms', clickhouse_backend.models.UInt16Field(default=0)),
                ('bytes_sent', clickhouse_backend.models.UInt32Field(default=0)),
            ],
            options={
                'ordering': ['-event_time'],
                'engine': clickhouse_backend.models.MergeTree(index_granularity=8192, order_by=('event_date', 'user_id', 'event_time'), partition_by=clickhouse_backend.models.toYYYYMM('event_date')),
                'indexes': [clickhouse_backend.models.Index(fields=['user_id'], granularity=1, name='event_user_id_bloom_idx', type=clickhouse_backend.models.BloomFilter(0.01)), clickhouse_backend.models.Index(fields=['event_type'], granularity=4, name='event_type_set_idx', type=clickhouse_backend.models.Set(100))],
                'constraints': [models.CheckConstraint(condition=models.Q(('response_time_ms__gte', 0), ('response_time_ms__lte', 60000)), name='response_time_range')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', clickhouse_backend.models.UInt32Field(primary_key=True, serialize=False)),
                ('updated_at', clickhouse_backend.models.DateTimeField(default=django.utils.timezone.now)),
                ('name', clickhouse_backend.models.StringField(max_length=200)),
                ('email', clickhouse_backend.models.StringField(max_length=320)),
                ('registration_date', clickhouse_backend.models.DateField()),
                ('last_activity', clickhouse_backend.models.DateTimeField()),
                ('total_sessions', clickhouse_backend.models.UInt32Field(default=0)),
                ('total_page_views', clickhouse_backend.models.UInt32Field(default=0)),
            ],
            options={
                'ordering': ['-last_activity'],
                'engine': clickhouse_backend.models.ReplacingMergeTree('updated_at', order_by='user_id'),
                'indexes': [clickhouse_backend.models.Index(fields=['email'], granularity=1, name='email_bloom_idx', type=clickhouse_backend.models.BloomFilter(0.001))],
                'constraints': [models.CheckConstraint(condition=models.Q(('total_page_views__gte', models.F('total_sessions'))), name='sessions_views_relation')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
